-- MySQL Script generated by MySQL Workbench
-- Mon Aug 17 22:29:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qrindrv3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qrindrv3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qrindrv3` DEFAULT CHARACTER SET utf8 ;
USE `qrindrv3` ;

-- -----------------------------------------------------
-- Table `qrindrv3`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrindrv3`.`matches` (
  `matchId` INT NOT NULL AUTO_INCREMENT,
  `matchConfig` INT(2) NOT NULL DEFAULT 0,
  `matchHash` VARCHAR(64) NOT NULL,
  `matchSecret` VARCHAR(64) NOT NULL,
  `matchPlayerOne` VARCHAR(24) NOT NULL,
  `matchPlayerTwo` VARCHAR(24) NOT NULL,
  `matchFormat` INT(1) NOT NULL DEFAULT 0,
  `matchCointoss` INT(1) NOT NULL DEFAULT 0,
  `matchCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `idmatches_UNIQUE` (`matchId` ASC),
  PRIMARY KEY (`matchId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindrv3`.`matchesSteps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrindrv3`.`matchesSteps` (
  `matchStepId` INT NOT NULL AUTO_INCREMENT,
  `matchStepMatch` INT NOT NULL,
  `matchStepValue` INT(2) NOT NULL,
  `matchStepType` VARCHAR(5) NULL,
  `matchStepCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`matchStepId`),
  UNIQUE INDEX `matchStepId_UNIQUE` (`matchStepId` ASC),
  INDEX `fk_matchesSteps_matches_idx` (`matchStepMatch` ASC),
  CONSTRAINT `fk_matchesSteps_matches`
    FOREIGN KEY (`matchStepMatch`)
    REFERENCES `qrindrv3`.`matches` (`matchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindrv3`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrindrv3`.`blogs` (
  `blogId` INT NOT NULL AUTO_INCREMENT,
  `blogTitle` VARCHAR(250) NOT NULL,
  `blogThumbnail` CHAR(200) NOT NULL,
  `blogHref` CHAR(200) NOT NULL,
  `blogGame` VARCHAR(32) NOT NULL,
  `blogCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`blogId`),
  UNIQUE INDEX `blogId_UNIQUE` (`blogId` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
