-- MySQL Script generated by MySQL Workbench
-- Sun Jun  7 18:44:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qrindr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qrindr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qrindr` DEFAULT CHARACTER SET utf8 ;
USE `qrindr` ;

-- -----------------------------------------------------
-- Table `qrindr`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrindr`.`games` (
  `gameId` INT NOT NULL AUTO_INCREMENT,
  `gameName` VARCHAR(45) NOT NULL DEFAULT 'Quake Live',
  `gameAbbreviation` VARCHAR(3) NOT NULL DEFAULT 'QL',
  `gameAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`gameId`),
  UNIQUE INDEX `idgames_UNIQUE` (`gameId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindr`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrindr`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(32) NOT NULL,
  `userSecret` VARCHAR(64) NOT NULL,
  `userAlias_QC` CHAR(24) NOT NULL,
  `userAlias_DBT` CHAR(24) NOT NULL,
  `userCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC),
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindr`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrindr`.`matches` (
  `matchId` INT NOT NULL AUTO_INCREMENT,
  `matchHash` VARCHAR(32) NOT NULL,
  `matchUserOne` INT NOT NULL,
  `matchUserSecond` INT NOT NULL,
  `matchGame` INT NOT NULL,
  `matchCreated` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`matchId`),
  UNIQUE INDEX `idmatches_UNIQUE` (`matchId` ASC),
  INDEX `fk_matches_users_idx` (`matchUserOne` ASC),
  INDEX `fk_matches_users1_idx` (`matchUserSecond` ASC),
  INDEX `fk_matches_games1_idx` (`matchGame` ASC),
  CONSTRAINT `fk_matches_users`
    FOREIGN KEY (`matchUserOne`)
    REFERENCES `qrindr`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_users1`
    FOREIGN KEY (`matchUserSecond`)
    REFERENCES `qrindr`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_games1`
    FOREIGN KEY (`matchGame`)
    REFERENCES `qrindr`.`games` (`gameId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindr`.`matches_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrindr`.`matches_data` (
  `matchDataId` INT NOT NULL AUTO_INCREMENT,
  `matchDataUser` INT NOT NULL,
  `matchDataStep` INT NOT NULL,
  `matchDataValue` INT NOT NULL,
  PRIMARY KEY (`matchDataId`),
  UNIQUE INDEX `matchDataId_UNIQUE` (`matchDataId` ASC),
  INDEX `fk_matches_data_users1_idx` (`matchDataUser` ASC),
  CONSTRAINT `fk_matches_data_users1`
    FOREIGN KEY (`matchDataUser`)
    REFERENCES `qrindr`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
