-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 08:36:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qrindr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qrindr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qrindr` DEFAULT CHARACTER SET utf8 ;
USE `qrindr` ;

-- -----------------------------------------------------
-- Table `qrindr`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qrindr`.`games` ;

CREATE TABLE IF NOT EXISTS `qrindr`.`games` (
  `gameId` INT NOT NULL AUTO_INCREMENT,
  `gameName` VARCHAR(45) NOT NULL DEFAULT 'Quake Live',
  `gameAbbreviation` VARCHAR(3) NOT NULL DEFAULT 'QL',
  `gameAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`gameId`),
  UNIQUE INDEX `idgames_UNIQUE` (`gameId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindr`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qrindr`.`matches` ;

CREATE TABLE IF NOT EXISTS `qrindr`.`matches` (
  `matchId` INT NOT NULL AUTO_INCREMENT,
  `matchHash` VARCHAR(32) NOT NULL,
  `matchPlayerOne` VARCHAR(32) NOT NULL,
  `matchPlayerTwo` VARCHAR(32) NOT NULL,
  `matchGame` INT NOT NULL,
  `matchSecret` VARCHAR(16) NOT NULL,
  `matchCointoss` INT(1) NOT NULL DEFAULT 0,
  `matchCreated` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`matchId`),
  UNIQUE INDEX `idmatches_UNIQUE` (`matchId` ASC),
  INDEX `fk_matches_games1_idx` (`matchGame` ASC),
  CONSTRAINT `fk_matches_games1`
    FOREIGN KEY (`matchGame`)
    REFERENCES `qrindr`.`games` (`gameId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindr`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qrindr`.`users` ;

CREATE TABLE IF NOT EXISTS `qrindr`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userAuthId` VARCHAR(64) NOT NULL,
  `userName` VARCHAR(32) NOT NULL,
  `userAlias_QC` CHAR(24) NOT NULL,
  `userAlias_DBT` CHAR(24) NOT NULL,
  `userCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC),
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qrindr`.`matches_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qrindr`.`matches_data` ;

CREATE TABLE IF NOT EXISTS `qrindr`.`matches_data` (
  `matchDataId` INT NOT NULL AUTO_INCREMENT,
  `matchDataMatchId` INT NOT NULL,
  `matchDataPlayer` VARCHAR(32) NOT NULL,
  `matchDataStep` INT NOT NULL,
  `matchDataValue` INT NOT NULL,
  PRIMARY KEY (`matchDataId`),
  UNIQUE INDEX `matchDataId_UNIQUE` (`matchDataId` ASC),
  INDEX `fk_matches_data_matches1_idx` (`matchDataMatchId` ASC),
  CONSTRAINT `fk_matches_data_matches1`
    FOREIGN KEY (`matchDataMatchId`)
    REFERENCES `qrindr`.`matches` (`matchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `qrindr`.`games`
-- -----------------------------------------------------
START TRANSACTION;
USE `qrindr`;
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Quake Champions Duel - Best of 3', 'QC', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Quake Champions Duel - Best of 5', 'QC', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Diabotical Duel - Best of 3', 'DBT', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Diabotical Duel - Best of 5', 'DBT', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Diabotical Duel - Best of 7', 'DBT', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Diabotical MacGuffin - Best of 3', 'DBT', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Diabotical MacGuffin - Best of 5', 'DBT', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Quake Live Duel - Best of 3', 'QL', DEFAULT);
INSERT INTO `qrindr`.`games` (`gameId`, `gameName`, `gameAbbreviation`, `gameAdded`) VALUES (DEFAULT, 'Quake Live Duel - Best of 5', 'QL', DEFAULT);

COMMIT;

